### ISSUE TITLE
Where are defences code? 

### ISSUE THREAD

**Issue by mhsamavatian** [cleverhans-lab/cleverhans#1152]

**Comment by arunpalaniappan** [comment]
For versions before 2019-04-05, defenses are implemented in `utils_tf.py`. The `cleverhans.utils_tf.train` is depreciated after 2019-04-05. The later defenses are implemented in `train.py' ( `cleverhans.train.train`).

**Comment by jonasguan** [comment]
We're planning to implement more defenses in TF2, PyTorch and Jax in our upcoming updates. I know the `defenses/` directory has stayed empty for a while, but we plan to work on it soon, stay tuned!
