### ISSUE TITLE
use JSMA to a model with dropout layer results in an error

### ISSUE THREAD

**Issue by freefreesea** [cleverhans-lab/cleverhans#1153]
***The issue tracker should only be used to report bugs or feature requests. If you are looking for support from other library users, please ask a question on [StackOverflow](https://stackoverflow.com/questions/tagged/cleverhans).***

**Describe the bug**
I trid to reproduce the paper:Distillation as a defense to adversarial perturbations against deep neural networks. The first network used in MNIST, but the code cannot work. IF I drop the dropout layer ,it works well.
Here's my core code:
***********
model = Keras.models.load_model("early trained")
jsma = SaliencyMapMethod(KerasModelWrapper(model),sess=sess)
jsma_para = {'theta' : 1.,
     'gamma': 1.,
     'clip_min' : 0.,
     'clip_max' : 1.
             }
attack_x = jsma.generate(x,**jsma_para)
adversarial_image = sess.run(attack_x, feed_dict={x: (np.expand_dims(x_train[0],axis=0))})
***********

**To Reproduce**
1.set a model with dropout by Keras 
2.if dropout ,error

**Expected behavior**
tensorflow.python.framework.errors_impl.InternalError: Invalid loop structure: Mismatched parent frames for "while/while_context": "while/while_context" vs "". The node giving this error: node while/gradients/while/model_1/dropout_1/cond/mul_grad/Shape/Enter (defined at E:\env\Anaconda\lib\site-packages\cleverhans\attacks_tf.py:398) This is an internal bug, please file a bug report with instructions on how to reproduce the error.

**Screenshots**

**System configuration**
 - OS:win10
 - Python version:3.6.5
 - TensorFlow version:tensorflow-gpu 1.12.0

**Comment by carlini** [comment]
This is an internal bug with tensorflow. We are still waiting for a fix tensorflow/tensorflow#23166

**Comment by freefreesea** [comment]
thank you so much
