### ISSUE TITLE
NameError: name '__file__' is not defined

### ISSUE THREAD

**Issue by shivam2197** [cleverhans-lab/cleverhans#1169]
I am getting a name error as
`<ipython-input-1-4fbd91cef426> in <module>
    224   flags.DEFINE_boolean('load_model', LOAD_MODEL,
    225                        'Load saved model or train.')
--> 226   tf.app.run()

~\.conda\envs\tf2_env\lib\site-packages\tensorflow\python\platform\app.py in run(main, argv)
    124   # Call the main function, passing through any arguments
    125   # to the final program.
--> 126   _sys.exit(main(argv))
    127 
    128 

<ipython-input-1-4fbd91cef426> in main(argv)
    203 def main(argv=None):
    204   from cleverhans_tutorials import check_installation
--> 205   check_installation(__file__)
    206 
    207   mnist_tutorial(nb_epochs=FLAGS.nb_epochs,`

**Comment by jonasguan** [comment]
Hi, we're currently undergoing a major revamp, so I'm closing the issue for now since it's been inactive for a while. If you're still experiencing problems, feel free to reopen with a new issue and mention this one.
