### ISSUE TITLE
Correction in tool.py file (cleverhans/examples/adversarial_asr/tool.py )

### ISSUE THREAD

**Issue by saumya0303** [cleverhans-lab/cleverhans#1170]
Hi team,
             In transform class while calculating PSD it was written **self.scale = 8. / 3.** it should be **self.scale=np.sqrt(8.0/3.)** Please find the attached document for calculation of [PSD.]

**tool.py code**
class Transform(object):
 
    def __init__(self, window_size):
        self.scale = 8. / 3.

In generate_masking_threshold.py (cleverhans/examples/adversarial_asr/generate_masking_threshold.py) scaling factor is taken as **np.sqrt(8.0/3.)** 

**generate_masking_threshold.py code**

         def compute_PSD_matrix(audio, window_size):
                win = np.sqrt(8.0/3.) * librosa.core.stft(audio, center=False)

![Screenshot 2020-06-10 at 10 34 32 AM](https://user-images.githubusercontent.com/15156552/84229063-48ef0980-ab06-11ea-846c-ea363d78684b.png)
![Screenshot 2020-06-10 at 10 35 05 AM](https://user-images.githubusercontent.com/15156552/84229088-57d5bc00-ab06-11ea-8931-55283ea9bceb.png)

**Comment by htZhang25** [comment]
I read this paper recently. I agree with you. In transform class it seems the stft result will only be multiplied by the square root of 8./3.. In generate_masking_threshold.py, it is consistent with this reference you have pasted.

**Comment by jonasguan** [comment]
Thanks for bringing this up! Unfortunately, we're undergoing some major updates as we move away from TF 1.x to TF 2, PyTorch and Jax, and we currently don't have the bandwidth to verify and fix bugs in older examples. I'll have to close the issue for now, but if you find we have the same problem after our updates to CleverHans v4, feel free to reopen the issue or submit a PR.
