### ISSUE TITLE
Flags missing from cleverhans.compat 

### ISSUE THREAD

**Issue by Andymic** [cleverhans-lab/cleverhans#1171]
**Description**
flags no longer exist in cleverhans.compat, therefore it cannot be imported. 

**To Reproduce**
pip install cleverhans or git clone https://github.com/tensorflow/cleverhans

**Expected behavior**
I expected lags to be in cleverhans.compat. The side of effect is that cleverhans_tutorial i.e. mnist_tutorial_tf.py no longer works

**System configuration**
 - Ubuntu 20.04
 - python2.7
 - TensorFlow1.7

**Comment by jonasguan** [comment]
Hi @Andymic , thanks for opening the issue and proactively making a PR. Unfortunately we've discontinued support for TF1 as we're working on a new version of the library that will support TF2, PyTorch and Jax. It'll be released very soon. I'll have to close the issue and PR for now, but if you meet similar problems in the new version please let us know.
