### ISSUE TITLE
Cannot use the model_zoo.my_cnn?

### ISSUE THREAD

**Issue by YoungBigBird1985** [cleverhans-lab/cleverhans#1177]
from cleverhans.model_zoo.my_cnn import MyCNN
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named my_cnn

**Comment by jonasguan** [comment]
Hi @YoungBigBird1985 , I don't believe there is a my_cnn module. Can you double check your code?

We're currently undergoing a major revamp, so I'm closing the issue for now. If you're still experiencing problems, feel free to reopen with a new issue.
