### ISSUE TITLE
@tf.keras.utils.register_keras_serializable(package="Addons") AttributeError: module 'tensorflow.keras.utils' has no attribute 'register_keras_serializable'

### ISSUE THREAD

**Issue by azamAviage** [cleverhans-lab/cleverhans#1178]
I'm trying to install Cleverhans and run one of the examples.

I was able to install Cleverhans but when running an example under tutorial directory, I get error.

I'm using tensorflow  1.9.0, Keras 2.4, Cleverhans 3.0.1.

For each tensorflow version I'm getting a specific error. When I want to resolve the issue, I need to change the tensorflow version and with each version I'm getting new series of error. 

So, what are the compatibility requirement between Cleverhans, Tensorflow and Keras to make Cleverhans work?

**Comment by rufengma** [comment]
Same, cleverhans require Tensorflow 1.x, but Addons is a 2.x thing. Can anyone fix this?

**Comment by rufengma** [comment]
> I'm trying to install Cleverhans and run one of the examples.
> 
> I was able to install Cleverhans but when running an example under tutorial directory, I get error.
> 
> I'm using tensorflow 1.9.0, Keras 2.4, Cleverhans 3.0.1.
> 
> For each tensorflow version I'm getting a specific error. When I want to resolve the issue, I need to change the tensorflow version and with each version I'm getting new series of error.
> 
> So, what are the compatibility requirement between Cleverhans, Tensorflow and Keras to make Cleverhans work?

Did you find away to fix it? The cleverhans version I could use currently is 2.1.0

**Comment by jonasguan** [comment]
Hey friends, unfortunately we don't support TF 1.9, and we're dropping support for TF 1.x soon. However, we are planning major updates soon that will include support for TF 2, PyTorch and Jax.
