### ISSUE TITLE
Cannot download dataset/images under nips17_adversarial_competition/dataset

### ISSUE THREAD

**Issue by Wrathar** [cleverhans-lab/cleverhans#1180]
***The issue tracker should only be used to report bugs or feature requests. If you are looking for support from other library users, please ask a question on [StackOverflow](https://stackoverflow.com/questions/tagged/cleverhans).***

**Describe the bug**
I tried to run the "download_images.py" file under this directory but all downloads of all images failed and no images were downloaded

**To Reproduce**
1. Go to 'cleverhans/examples/nips17_adversarial_competition/dataset'
2. Run "python download_images.py --input_file=${CSV_FILE} --output_dir=${OUTPUT_DIR}"

**Expected behavior**
The images should be generated in the output directory that I created but it was empty.

**Screenshots**
![image](https://user-images.githubusercontent.com/61144786/92851491-3398bc80-f420-11ea-948d-b34718c04d14.png)

**System configuration**
 - OS: Linux
 - Python version: 2.7.12
 - TensorFlow version: 1.1.0

**Comment by jonasguan** [comment]
Hi @Wrathar , thanks for bringing this up, but unfortunately we can't offer maintenance/support for code in the `examples/` directory. It looks like the image links are expired. I'll try to see what I can do later, but we may have to just delete that example since those images are not hosted by us.
