### ISSUE TITLE
Hosted documentation?

### ISSUE THREAD

**Issue by redwrasse** [cleverhans-lab/cleverhans#1185]
I can't seem to find usable documentation for cleverhans. There is https://cleverhans.readthedocs.io/en/latest/, 
which I presume matches the `docs/` directory. Is there something forthcoming, with say getting started, tutorials, concepts, etc?
Thanks.

**Comment by adam-dziedzic** [comment]
We're going to update the documentation in a few days. Stay in touch.

**Comment by jonasguan** [comment]
You can now find the API documentation at [https://cleverhans-lab.github.io/cleverhans/](https://cleverhans-lab.github.io/cleverhans/). To get started, I recommend going through the README. We also have some major updates planned, which will include new tutorials, stay tuned :)

**Comment by redwrasse** [comment]
Excellent, thanks!
