### ISSUE TITLE
There is no torch package when use command pip install cleverhans!Why?HELP!

### ISSUE THREAD

**Issue by RSMung** [cleverhans-lab/cleverhans#1209]
I use command pip install cleverhans to install this package.
Then I write code follow this tutorials: https://github.com/cleverhans-lab/cleverhans/blob/master/tutorials/torch/cifar10_tutorial.py
But I find out that pycharm give error to me in this line:
from cleverhans.torch.attacks.fast_gradient_method import fast_gradient_method

I can't understand why there is this problem.
How can I solve it?
please help
thank you very much

**Comment by RSMung** [comment]
Pycharm reports that it can't find reference torch, so I can not use the method fast_gradient_method.
It is so strange

**Comment by RSMung** [comment]
I use this way---Installation for development to install this package, then it work well.
But this way is not convenient.
I still want to know why the way that I use pip command to install is not work well. 

Otherwise I find out that this package's method cant work in segmentation tasks due to the loss function.

**Comment by tejuafonja** [comment]
Hi @RSMung, thanks for reporting this. I'm glad you were able to get it to work. The pip command is still using version 3, and we are in the process of upgrading to version 4. Once that is complete, you should be able to install pip without having to install the library for development. 

I'm going to close this issue but feel free to reopen it if you have more questions.
