### ISSUE TITLE
Survey on globally distributed software engineering

### ISSUE THREAD

**Issue by AsWali** [cleverhans-lab/cleverhans#1210]
Hey there. 

We are doing a survey on globally distributed software engineering focused on open source projects. If you have some spare time we would really appreciate your response. The form takes about 10 minutes. Thanks in advance!
Survey can be found [here](https://forms.gle/N1TnifRuCYHrCY9JA)

**Comment by jonasguan** [comment]
Hi @AsWali , I'm closing this since you've never been a contributor, and are here solely to advertise your survey. I recommend that you reach out to repo maintainers prior to posting surveys like this, otherwise it's an abuse of the issues board.
