### ISSUE TITLE
ModuleNotFoundError: No module named 'cleverhans.attacks'

### ISSUE THREAD

**Issue by AbdulMustafa97** [cleverhans-lab/cleverhans#1216]
I am getting this type of error for a lot of other cleverhans packages just like **cleverhans.utils_tf**, **cleverhans.model**,  **cleverhans.utils_keras**.  

I am running on Google Colaboratory using following libraries versions:
CleverHans 4.0.0
Tensorflow 2.6, 2.4, 1.13 tried different versions.
Python 3.7.11

@aam-at @esigler @catherio @nottombrown @goodfeli
![Capture](https://user-images.githubusercontent.com/51948496/131958881-bcf5fcd4-d182-4c05-8368-02e453f4ee34.PNG)

**Comment by AbdulMustafa97** [comment]
@tejuafonja Can you please help to resolve this error?

Thanks.

**Comment by AbdulMustafa97** [comment]
There was a mismatch in the TensorFlow and Cleverhans library. Fix this bug with downgrade the CleverHans to 3.0 and TensorFlow to 1.14.

**Comment by tejuafonja** [comment]
Hi @AbdulMustafa97, thanks for reporting this error and I'm happy to hear that you were able to resolve it.

**Comment by tejuafonja** [comment]
Hi @AbdulMustafa97, thanks for reporting this error and I'm happy to hear that you were able to resolve it.
