### ISSUE TITLE
Update tutorials to use multi-GPU eval where appropriate

### ISSUE THREAD

**Issue by goodfeli** [cleverhans-lab/cleverhans#550]
Note that we should not deprecate single-GPU eval nor should we update the tutorials to use multi-GPU in *all* cases. The larger graph for multi-GPU means that the first few runs of multi-GPU are slow, so it's only worth replacing use cases that have enough runs to justify the high startup cost.

**Comment by jonasguan** [comment]
Closing since we're stopping support for version < 4.
