### ISSUE TITLE
Consider moving to Google Cloud Build

### ISSUE THREAD

**Issue by npapernot** [cleverhans-lab/cleverhans#740]
Benefits would include:

- Speed up tests by configuring Dockerfile to use an image with everything preinstalled
- Use an SSD or an extra fast CPU
- Build everything in a RAM disk

Closes #676 
Closes #677
Closes #638

**Comment by souravsingh** [comment]
I am willing to help with the issue. How do I start?

**Comment by goodfeli** [comment]
Sorry, we should update the issue. We tried using Google Cloud Build and found that it was missing one feature we wanted. We're waiting for that feature to be released publicly and then we'll make the switch. Thank you for offering to help. We'll ping you again when the GCB feature is out.

**Comment by jonasguan** [comment]
Closing as we're moving to Github Actions for CI.
