### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by goodfeli** [cleverhans-lab/cleverhans#836]
This pytorch test fails on unrelated Travis PRs reasonably often. It's usually fixed just by restarting the build.

FAIL: test_mnist_tutorial_pytorch (test_mnist_tutorial_pytorch.TestMNISTTutorialPytorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/tensorflow/cleverhans/tests_pytorch/test_mnist_tutorial_pytorch.py", line 23, in test_mnist_tutorial_pytorch
    self.assertLess(report.clean_train_adv_eval, 0.10)
AssertionError: 0.1021021021021021 not less than 0.1

**Comment by jonasguan** [comment]
Closing as we drop support for version < 4.
