### ISSUE TITLE
Add some unit tests that graph caching doesn't have false positives

### ISSUE THREAD

**Issue by goodfeli** [cleverhans-lab/cleverhans#840]
These tests should fail if run prior to https://github.com/tensorflow/cleverhans/pull/819

e.g., I think it was possible to cache an untargeted attack by passing y=None and y_target=None, then get a cache hit when trying to do a targeted attack by passing y_target = <some value>.

**Comment by jonasguan** [comment]
Closing as we drop support for version < 4.
