### ISSUE TITLE
Add a script demonstrating how to evaluate defenses against adversarial examples according to best practices

### ISSUE THREAD

**Issue by GuanxiongLiu** [cleverhans-lab/cleverhans#985]
**Is your feature request related to a problem? Please describe.**
Hi all, I'm doing research on designing defensive methods. From the references I used and my own experience, a standard of the evaluation process could largely benefit the whole community. Since different evaluation process is conducted, it is hard for people to evaluate their proposed defense with the state-of-the-art. Moreover, some weakly designed evaluation may result in the obfuscated gradient effect which is already identified by @carlini.

**Describe the solution you'd like**
As a reference or a suggestion, CleverHans could offer an evaluation demo to the whole community. In this demo, a detailed evaluation plan could be offered which includes a selection of different adversarial examples, different evaluation flows for white-box/black-box defenses and even the computational cost of proposed defenses.

**Comment by npapernot** [comment]
No progress has been made on this issue yet, but for now we recommend reading the following report: https://github.com/evaluating-adversarial-robustness/adv-eval-paper

**Comment by jonasguan** [comment]
Closing this issue for now since it's inactive for a while, and we currently don't have plans to design/implement a standard evaluation process. I'll reopen if more people are interested in discussing this.
